<a href="https://colab.research.google.com/github/WassimXcx-dotcom/EventsManagerProject/blob/main/notebooks/controle_numpy_matplotlib_wassim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :  
Filière :  
Année universitaire :

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [56]:
# Votre code ici
import numpy as np
import matplotlib.pyplot as plt

# Importer iris dataset avec numpy

features = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=(0,1,2,3,4))
species = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=(5),dtype=str)

#Le méthode set_portions pour la désactivation de le notation exponentielle
np.set_printoptions(
    suppress=True,
    precision=3
)

print(features)
print(features.shape)
print(species)
print(species.shape)

[[  1.    5.1   3.5   1.4   0.2]
 [  2.    4.9   3.    1.4   0.2]
 [  3.    4.7   3.2   1.3   0.2]
 [  4.    4.6   3.1   1.5   0.2]
 [  5.    5.    3.6   1.4   0.2]
 [  6.    5.4   3.9   1.7   0.4]
 [  7.    4.6   3.4   1.4   0.3]
 [  8.    5.    3.4   1.5   0.2]
 [  9.    4.4   2.9   1.4   0.2]
 [ 10.    4.9   3.1   1.5   0.1]
 [ 11.    5.4   3.7   1.5   0.2]
 [ 12.    4.8   3.4   1.6   0.2]
 [ 13.    4.8   3.    1.4   0.1]
 [ 14.    4.3   3.    1.1   0.1]
 [ 15.    5.8   4.    1.2   0.2]
 [ 16.    5.7   4.4   1.5   0.4]
 [ 17.    5.4   3.9   1.3   0.4]
 [ 18.    5.1   3.5   1.4   0.3]
 [ 19.    5.7   3.8   1.7   0.3]
 [ 20.    5.1   3.8   1.5   0.3]
 [ 21.    5.4   3.4   1.7   0.2]
 [ 22.    5.1   3.7   1.5   0.4]
 [ 23.    4.6   3.6   1.    0.2]
 [ 24.    5.1   3.3   1.7   0.5]
 [ 25.    4.8   3.4   1.9   0.2]
 [ 26.    5.    3.    1.6   0.2]
 [ 27.    5.    3.4   1.6   0.4]
 [ 28.    5.2   3.5   1.5   0.2]
 [ 29.    5.2   3.4   1.4   0.2]
 [ 30.    4.7   3.2   1.6   0.2]
 [ 31.    

### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [73]:
# Votre code ici
#L'étape de séparation (A2) est omise car features et species sont déjà isolés et correctement typés (numérique/string) lors de l'importation corrigée.
#Exclure la premiere colone ID
features = features[:,:]
print(features)
print(species)

[[3.1 1.5 0.2]
 [3.6 1.4 0.2]
 [3.9 1.7 0.4]
 [3.4 1.4 0.3]
 [3.4 1.5 0.2]
 [2.9 1.4 0.2]
 [3.1 1.5 0.1]
 [3.7 1.5 0.2]
 [3.4 1.6 0.2]
 [3.  1.4 0.1]
 [3.  1.1 0.1]
 [4.  1.2 0.2]
 [4.4 1.5 0.4]
 [3.9 1.3 0.4]
 [3.5 1.4 0.3]
 [3.8 1.7 0.3]
 [3.8 1.5 0.3]
 [3.4 1.7 0.2]
 [3.7 1.5 0.4]
 [3.6 1.  0.2]
 [3.3 1.7 0.5]
 [3.4 1.9 0.2]
 [3.  1.6 0.2]
 [3.4 1.6 0.4]
 [3.5 1.5 0.2]
 [3.4 1.4 0.2]
 [3.2 1.6 0.2]
 [3.1 1.6 0.2]
 [3.4 1.5 0.4]
 [4.1 1.5 0.1]
 [4.2 1.4 0.2]
 [3.1 1.5 0.1]
 [3.2 1.2 0.2]
 [3.5 1.3 0.2]
 [3.1 1.5 0.1]
 [3.  1.3 0.2]
 [3.4 1.5 0.2]
 [3.5 1.3 0.3]
 [2.3 1.3 0.3]
 [3.2 1.3 0.2]
 [3.5 1.6 0.6]
 [3.8 1.9 0.4]
 [3.  1.4 0.3]
 [3.8 1.6 0.2]
 [3.2 1.4 0.2]
 [3.7 1.5 0.2]
 [3.3 1.4 0.2]
 [3.2 4.7 1.4]
 [3.2 4.5 1.5]
 [3.1 4.9 1.5]
 [2.3 4.  1.3]
 [2.8 4.6 1.5]
 [2.8 4.5 1.3]
 [3.3 4.7 1.6]
 [2.4 3.3 1. ]
 [2.9 4.6 1.3]
 [2.7 3.9 1.4]
 [2.  3.5 1. ]
 [3.  4.2 1.5]
 [2.2 4.  1. ]
 [2.9 4.7 1.4]
 [2.9 3.6 1.3]
 [3.1 4.4 1.4]
 [3.  4.5 1.5]
 [2.7 4.1 1. ]
 [2.2 4.5 1.5]
 [2.5 3.9 

### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [58]:
# Votre code ici
print(features[:5])

[[1.  5.1 3.5 1.4 0.2]
 [2.  4.9 3.  1.4 0.2]
 [3.  4.7 3.2 1.3 0.2]
 [4.  4.6 3.1 1.5 0.2]
 [5.  5.  3.6 1.4 0.2]]


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [59]:
# Votre code ici
# Souvent la variable sepal_lenght contient la deuxiemme colonne de features avec index 1
sepal_length = features[:,1]
print(sepal_length)
print(sepal_length.size)
print(sepal_length.dtype)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
150
float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [60]:
# Votre code ici
setosa_features = features[:50]
print(setosa_features)

[[ 1.   5.1  3.5  1.4  0.2]
 [ 2.   4.9  3.   1.4  0.2]
 [ 3.   4.7  3.2  1.3  0.2]
 [ 4.   4.6  3.1  1.5  0.2]
 [ 5.   5.   3.6  1.4  0.2]
 [ 6.   5.4  3.9  1.7  0.4]
 [ 7.   4.6  3.4  1.4  0.3]
 [ 8.   5.   3.4  1.5  0.2]
 [ 9.   4.4  2.9  1.4  0.2]
 [10.   4.9  3.1  1.5  0.1]
 [11.   5.4  3.7  1.5  0.2]
 [12.   4.8  3.4  1.6  0.2]
 [13.   4.8  3.   1.4  0.1]
 [14.   4.3  3.   1.1  0.1]
 [15.   5.8  4.   1.2  0.2]
 [16.   5.7  4.4  1.5  0.4]
 [17.   5.4  3.9  1.3  0.4]
 [18.   5.1  3.5  1.4  0.3]
 [19.   5.7  3.8  1.7  0.3]
 [20.   5.1  3.8  1.5  0.3]
 [21.   5.4  3.4  1.7  0.2]
 [22.   5.1  3.7  1.5  0.4]
 [23.   4.6  3.6  1.   0.2]
 [24.   5.1  3.3  1.7  0.5]
 [25.   4.8  3.4  1.9  0.2]
 [26.   5.   3.   1.6  0.2]
 [27.   5.   3.4  1.6  0.4]
 [28.   5.2  3.5  1.5  0.2]
 [29.   5.2  3.4  1.4  0.2]
 [30.   4.7  3.2  1.6  0.2]
 [31.   4.8  3.1  1.6  0.2]
 [32.   5.4  3.4  1.5  0.4]
 [33.   5.2  4.1  1.5  0.1]
 [34.   5.5  4.2  1.4  0.2]
 [35.   4.9  3.1  1.5  0.1]
 [36.   5.   3.2  1.

# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [61]:
# Votre code ici
moyenne = np.mean(features,axis=0)
print(moyenne)

[75.5    5.843  3.054  3.759  1.199]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [62]:
# Votre code ici
min,max = np.min(features[:,3]),np.max(features[:,3])
print(min,max)

1.0 6.9


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [63]:
# Votre code ici
normalized_petals = features[:,3] / max
print(normalized_petals)

[0.203 0.203 0.188 0.217 0.203 0.246 0.203 0.217 0.203 0.217 0.217 0.232
 0.203 0.159 0.174 0.217 0.188 0.203 0.246 0.217 0.246 0.217 0.145 0.246
 0.275 0.232 0.232 0.217 0.203 0.232 0.232 0.217 0.217 0.203 0.217 0.174
 0.188 0.217 0.188 0.217 0.188 0.188 0.188 0.232 0.275 0.203 0.232 0.203
 0.217 0.203 0.681 0.652 0.71  0.58  0.667 0.652 0.681 0.478 0.667 0.565
 0.507 0.609 0.58  0.681 0.522 0.638 0.652 0.594 0.652 0.565 0.696 0.58
 0.71  0.681 0.623 0.638 0.696 0.725 0.652 0.507 0.551 0.536 0.565 0.739
 0.652 0.652 0.681 0.638 0.594 0.58  0.638 0.667 0.58  0.478 0.609 0.609
 0.609 0.623 0.435 0.594 0.87  0.739 0.855 0.812 0.841 0.957 0.652 0.913
 0.841 0.884 0.739 0.768 0.797 0.725 0.739 0.768 0.797 0.971 1.    0.725
 0.826 0.71  0.971 0.71  0.826 0.87  0.696 0.71  0.812 0.841 0.884 0.928
 0.812 0.739 0.812 0.884 0.812 0.797 0.696 0.783 0.812 0.739 0.739 0.855
 0.826 0.754 0.725 0.754 0.783 0.739]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [64]:
# Votre code ici
versicolor = features[50:100]
cumsumLong = np.cumsum(versicolor[:,3])
print(cumsumLong[:10])

[ 4.7  9.2 14.1 18.1 22.7 27.2 31.9 35.2 39.8 43.7]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [65]:
# Votre code ici

cumsumLarg= np.cumsum(versicolor[:,4])
print(cumsumLarg[:10])

[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [66]:
# Votre code ici
print(np.unique(species))

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [68]:
# Votre code ici
# Exclure la première colonne (ID) qui n'est pas une feature
features_data = features[:, 1:]

# Maintenant, la forme de features_data est (150, 4), ce qui correspond à 150 * 4 = 600 éléments.
# La nouvelle forme (3, 50, 4) nécessite 3 * 50 * 4 = 600 éléments.
features_by_species = features_data.reshape(3,50,4)
print(features_by_species)

ValueError: cannot reshape array of size 750 into shape (3,50,4)

### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [ ]:
# Votre code ici


### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [ ]:
# Votre code ici


### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [ ]:
# Votre code ici


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [ ]:
# Votre code ici


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [ ]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [ ]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [ ]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [ ]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [ ]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [ ]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [ ]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [ ]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [ ]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [ ]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [ ]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...